GOOGLE_API_KEY = ""
# .streamlit/secrets.toml
GOOGLE_API_KEYS = [
    "AIzaSyDD2eYLg49qs9UI0Nd0ZdodSACLrQF579o",
    "AIzaSyA-kNrM-fsTCr6TN0zrb0y6mfdQb_RdgEI",
    "AIzaSyBT9UA5JSgKSHjdER7dJkbbHO2-sIhFows"
]